java_library(
    name = "junit5_launcher",
    srcs = ["JUnit5Launcher.java"],
    visibility = ["//visibility:public"],
    deps = [
        "@maven//:org_junit_platform_junit_platform_console",
    ],
)